apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: starlight-minimalistic-theme
  namespace: starlight-minimalistic-theme
spec:
  secretName: starlight-minimalistic-theme
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "starlight-minimalistic-theme.trueberryless.org"
